# Generated by Django 4.2.5 on 2024-02-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliderpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(max_length=500)),
                ('slider_paragraph', models.CharField(max_length=200)),
                ('slider_photo', models.ImageField(default='No images', upload_to='Slider Photo/')),
            ],
        ),
    ]
