# Generated by Django 4.2.5 on 2024-02-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toonify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcedureHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pro_heading', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProcedureTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_pro_paragraph', models.CharField(max_length=500)),
            ],
        ),
    ]
