# Generated by Django 4.2.5 on 2024-02-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Toonify', '0003_toonificationheading_toonificationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperparametersHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperparameters_heading', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HyperparametersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperparameters_photo', models.ImageField(default='No images', upload_to='HyperparametersImage/')),
            ],
        ),
    ]
